### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Gitstepn** [mgp25/classesMD5-64#1]
Please help to understand how to  use this. After extract whats the next step?

**Comment by mgp25** [comment]
The output is shown directly in command line. Is a utility you need to execute passing one argument (the apk file). Md5 classes.dex base64 encoded will be shown in command line

**Comment by Gitstepn** [comment]
i think you check. whatsapp android updated to 2.11.380.   i tried to use dex file and get the MD5. But i must be making some mistake.

**Comment by dp3rez** [comment]
Hello Gitstepn, I have removed the stuff you said I should remove (on the WART repository). How do we get in touch?

**Comment by mgp25** [comment]
If you have the latest md5, update user agent and version, then all is ok. The generation token method may be different in some bytes i have a fix for that :) already working. Not neccessary to update to .380. 378 is fine.

If you have any doubt just ask me

**Comment by mgp25** [comment]
@Gitstepn Oks

**Comment by andiappan-ar** [comment]
@mgp25 

Hi my device n version "WhatsApp/2.11.528 Android/5.0.2 Device/Moto G (2nd Generation)".

got response like: "{\"status\":\"fail\",\"reason\":\"bad_token\"}".

n what should b my WaSignature,WaClassesMd5.

**Comment by mgp25** [comment]
@andsi1 take the code from my code in WhatsAPI Official or WART

**Comment by andsi1** [comment]
@mgp25 in WARt-1.6.3.0 it shows following error when i request code.... pleas find image below

![image](https://cloud.githubusercontent.com/assets/11770345/6993289/7215ec08-db0d-11e4-80b7-ed139a372c54.png).

Also iam .net developer , no idea in php. ur whatsapi official is php coding.

please help me to get password...
