### ISSUE TITLE
Version not shown.

### ISSUE THREAD

**Issue by nobicycle** [mgp25/classesMD5-64#7]
Hi, I'm using Dec 11 2018 whatsapp.apk; com.whatsapp-452621.apk

$ python ./dexMD5.py ./com.whatsapp-452621.apk 
Version: 
ClassesDex: LWZdbS3sDl4vsY3XMFIHCQ==

Note the version is not shown.

Thanks for the app.

**Comment by mgp25** [comment]
Fixed in latest commit: https://github.com/mgp25/classesMD5-64/commit/abbe62b4aac510df9a588817fea912fa65fdb06a
